modLoader="javafml"
loaderVersion="[36,)"
license="BSD-3-Clause License"
issueTrackerURL="https://github.com/RealYusufIsmail/RealYusufIsmail_core/issues"
#logoFile="examplemod.png"
credits="realyusufismail"
authors="realyusufismail"

[[mods]]
modId="realyusufismailcore"
version="${file.jarVersion}"
displayName="Silent Lib"
updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/SilentLib/1.14/update.json"
description='''
    Shared library for Silent's mods
    '''

[[dependencies.realyusufismailcore]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="BOTH"
[[dependencies.realyusufismailcore]]
modId="minecraft"
mandatory=true
versionRange="[1.16.2,)"
ordering="NONE"
side="BOTH"