modLoader = "javafml"
loaderVersion = "[37,)"
license = "BSD-3-Clause License"
issueTrackerURL = "https://github.com/RealYusufIsmail/RealYusufIsmail_core/issues"
#logoFile="examplemod.png"
credits = "realyusufismail"
authors = "realyusufismail"

[[mods]]
modId = "realyusufismailcore"
version = "${file.jarVersion}"
displayName = "RealYusufIsmail Core"
updateJSONURL = "https://raw.githubusercontent.com/RealYusufIsmail/RealYusufIsmail-Core/1.17.1/update.json"
description = '''
Shared library for Yusuf Arfan Ismail's mods
 '''

[[dependencies.realyusufismailcore]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.realyusufismailcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"
