modLoader = "javafml"
loaderVersion = "[36,)"
license = "BSD-3-Clause License"
issueTrackerURL = "https://github.com/RealYusufIsmail-Mc-Mods/RealYusufIsmail-Core/issues"
#logoFile="examplemod.png"
credits = "realyusufismail"
authors = "RealYusufIsmail-Mc-Mods org"

[[mods]]
modId = "realyusufismailcore"
version = "${file.jarVersion}"
displayName = "RealYusufIsmail Core"
updateJSONURL = "https://forge.curseupdate.com/497372/realyusufismail-core"
description = '''
Shared library for Yusuf Arfan Ismail's mods
 '''

[[dependencies.realyusufismailcore]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.realyusufismailcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"